sonar.exclusions=**/apps/backend/prisma/migrations/**/*.sql,apps/backend/prisma/migrations/**/*.sql,**/dist/**,**/build/**,**/coverage/**,pnpm-lock.yaml
sonar.cpd.exclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.test.js,**/tests/**,**/__tests__/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=*:S1590
sonar.issue.ignore.multicriteria.e1.resourceKey=**/apps/backend/prisma/migrations/**/*.sql
