-- AlterEnum
ALTER TYPE "OrganisationPermissionKey" ADD VALUE IF NOT EXISTS 'VIEW_ORGANISATION_TRAINEES';
ALTER TYPE "OrganisationPermissionKey" ADD VALUE IF NOT EXISTS 'INVITE_ORGANISATION_TRAINEES';
ALTER TYPE "OrganisationPermissionKey" ADD VALUE IF NOT EXISTS 'REMOVE_ORGANISATION_TRAINEES';

ALTER TYPE "OrganisationUserStatus" ADD VALUE IF NOT EXISTS 'DISABLED';
