#!/usr/bin/env bash

set -euo pipefail

COMMIT_SUBJECT="$(head -n 1 "$1")"

if [[ "$COMMIT_SUBJECT" == Merge* ]]; then
  ./scripts/check-env-files.sh
  exit 0
fi

./scripts/check-commit-message.sh "$1"
pnpm exec commitlint --edit "$1"
